### ISSUE TITLE
Load Balancer Ressources / Data

### ISSUE THREAD

**Issue by benguichard** [outscale-dev/terraform-provider-outscale#11]
It would be great to have a ressource to manipulate Load Balancer. Thank You

**Comment by outscale-toa** [comment]
Hello,
Resolved in https://github.com/outscale-dev/terraform-provider-outscale/blob/master/CHANGELOG.md#020-november-30-2020
Thanks

**Comment by jerome-jutteau** [comment]
Hi,

Also check [outscale_load_balancer resource documentation](https://registry.terraform.io/providers/outscale-dev/outscale/latest/docs/resources/load_balancer) and [an example with a public load balancer](https://github.com/outscale-dev/terraform-provider-outscale/tree/master/examples/public_load_balancer).
