### ISSUE TITLE
Net Access Point / VPC endpoint resource

### ISSUE THREAD

**Issue by remisdemis** [outscale-dev/terraform-provider-outscale#12]
Hey,

are there any plans to add support for net access point (or VPC endpoints) to the terraform provider?

https://wiki.outscale.net/display/EN/About+VPC+Endpoints

Cheers,
Timon

**Comment by outscale-toa** [comment]
Hello,
Resolved in https://github.com/outscale-dev/terraform-provider-outscale/blob/master/CHANGELOG.md#030-april-06-2021
Thanks,
