### ISSUE TITLE
Resource for OSU Buckets ?

### ISSUE THREAD

**Issue by Floby** [outscale-dev/terraform-provider-outscale#14]
Is there a plan to support the creation / deletion of OSU buckets from terraform ?

**Comment by jerome-jutteau** [comment]
Hi, official outscale provider is currently based on [Outscale API](https://docs.outscale.com/api) which does not support object storage at this moment. A work around would be to use a S3-compatible terraform provider which can interact with OOS (Outscale Object Storage) service.

**Comment by rslinckx** [comment]
Currently the aws provider is not compatible with OOS as they try to get Encryption information when provisioning the bucket, and OOS answers with an error, stating that the encryption is not implemented, afaik it's the same with ansible s3_bucket module

**Comment by Floby** [comment]
ok :'(

**Comment by jerome-jutteau** [comment]
Hi!
As a work-around, we provided [an example](https://github.com/outscale-dev/terraform-oos-examples) on how to use s3 buckets and objects with a aws provider. Feel free to open an issue for further discussions.
