### ISSUE TITLE
outscale_image Blocks of type "bsu" are not expected here

### ISSUE THREAD

**Issue by bjacquin** [outscale-dev/terraform-provider-outscale#176]
### Terraform Version
```
terraform version
Terraform v1.2.2
on linux_amd64
+ provider registry.terraform.io/outscale-dev/outscale v0.5.4
```

### Terraform Configuration Files
```terraform
resource "outscale_image" "image01" {
  image_name = "terraform-omi-create"
  architecture = "x86_64"

  block_device_mappings {
    bsu {
      snapshot_id = "snap-ff597279"
    }
  }
}
```

### Debug Output
```
│ Error: Unsupported block type
│
│   on 99-image.tf line 6, in resource "outscale_image" "image01":
│    6:     bsu {
│
│ Blocks of type "bsu" are not expected here. Did you mean to define argument "bsu"? If so, use the equals sign to assign it a value.
```

Full trace is available in https://gist.github.com/bjacquin/278a8958a6c7e3bf953e4eba256dfe8a

### Expected Behavior
[Documentation regarding image](https://registry.terraform.io/providers/outscale-dev/outscale/latest/docs/resources/image) states that an image can be created from a snapshot id, however TF fails to plan with error mentioned above.

It is not clear to me how from existing documentation how such image should be created from a snapshot

### Actual Behavior
See `Debug Output`

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

**Comment by outscale-toa** [comment]
Hello @bjacquin,

Thanks for reaching us, we are looking at your issue

Best regards,
