### ISSUE TITLE
IOPS issue on 0.7.0 plugin

### ISSUE THREAD

**Issue by sylvain987** [outscale-dev/terraform-provider-outscale#255]
### Terraform Version
```
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/outscale v0.7.0
+ provider registry.terraform.io/hashicorp/vault v3.8.2
```

### Terraform Configuration Files
```
    block_device_mappings {
        device_name = "/dev/sda1"
        bsu {
            volume_size           = var.size_disk_system
            volume_type           = "gp2"
            delete_on_vm_deletion = true
        }
    }

```

### Crash Output
```
      ~ block_device_mappings {
            # (1 unchanged attribute hidden)

          ~ bsu {
              - iops                  = 1500 -> null # forces replacement
                # (3 unchanged attributes hidden)
            }
        }
```

### Expected Behavior
Terraform do not want to recreate the VM

### Actual Behavior
Terraform want to recreate the VM

### Steps to Reproduce
```
terraform init
terraform plan
```

### Additional Context

We migrate to 0.7.0 Outscale plugin. On the old VM, we put the root device on GP2 disk with 1500 IOPS even if on the reality, it's 100 or 150. With the new plugin, we need to put the IOPS value to null on GP2 disk. But Terraform want to destroy the VM because it want to transform the IOPS value to null.

So how can we configure the state or the configuration to use the new version of the plugin with the old VM ?

**Comment by outscale-toa** [comment]
Hi @sylvain987,
Thanks for reaching us, we are looking at your issue.

Best regards,

**Comment by FredericBerot-Armand** [comment]
Hi @sylvain987

I think you can try to replace "iops" value from 1500 to 0 in your file "terraform.tfstate".

From :
```terraform
  ...
  "block_device_mappings": [
    {
      "bsu": [
        {
          ...
          "iops": 1500,
          ...
        }
      ],
      ...
``` 

To :
```terraform
  ...
  "block_device_mappings": [
    {
      "bsu": [
        {
          ...
          "iops": 0,
          ...
        }
      ],
      ...
```

Hope this fix your problem ^^

**Comment by sylvain987** [comment]
Hello,
Perfect, thank for the tips.
Regards.
