### ISSUE TITLE
Support proxy protocol on outscale_load_balancer_policy

### ISSUE THREAD

**Issue by wibru** [outscale-dev/terraform-provider-outscale#46]
Hi, 
It is possible to add support for proxy protocol activation on loadbalancers please ?

### Current Terraform Version

```
1.x.x
```
### Attempted Solutions

I currently work around the lack of support with this:
```
resource "null_resource" "proxy_protocol" {
  # The outscale provider doesn't support proxy protocol activation at this time (20211229).
  provisioner "local-exec" {
    command = <<EOT
      aws elb create-load-balancer-policy \
        --load-balancer-name ${outscale_load_balancer.pub.load_balancer_name} \
        --policy-name proxyprotocol \
        --policy-type-name ProxyProtocolPolicyType \
        --endpoint https://lbu.eu-west-2.outscale.com \
      && aws elb set-load-balancer-policies-for-backend-server \
        --instance-port 443 \
        --load-balancer-name ${outscale_load_balancer.pub.load_balancer_name} \
        --policy-names proxyprotocol \
        --endpoint https://lbu.eu-west-2.outscale.com \
      && aws elb set-load-balancer-policies-for-backend-server \
        --instance-port 80 \
        --load-balancer-name ${outscale_load_balancer.pub.load_balancer_name} \
        --policy-names proxyprotocol \
        --endpoint https://lbu.eu-west-2.outscale.com
    EOT
  }
}

# https://docs.outscale.com/fr/userguide/Configurer-un-protocole-proxy-pour-vos-load-balancers.html
# DOESN'T WORK
#resource "outscale_load_balancer_policy" "proxy_protocol" {
#  load_balancer_name = outscale_load_balancer.pub.id
#  policy_name        = "proxy-protocol"
#  policy_type        = "ProxyProtocolPolicyType"
#}
```

**Comment by jerome-jutteau** [comment]
Hi @wibru , I let @outscale-toa or @outscale-mdr check that and come back to you, they should be available next week.

**Comment by outscale-toa** [comment]
Hi @wibru
Thanks for the issue.

The documentation you mentionned (https://docs.outscale.com/fr/userguide/Configurer-un-protocole-proxy-pour-vos-load-balancers.html) is working only when you use ``` aws-cli ``` to set load-balancer-policies.

for now to use the  ```Terraform oustcale provider``` you have to set  ```policy_type  = "load_balancer"  or  policy_type  = "app" ``` (https://registry.terraform.io/providers/outscale-dev/outscale/latest/docs/resources/load_balancer_policy)
```
[ ... ]

resource "outscale_load_balancer_policy" "proxy_protocol" {
   load_balancer_name = outscale_load_balancer.pub.id
   policy_name        = "proxy-protocol"
   policy_type        = "load_balancer"
}
```
We are working around to synchronize the two configuration

Best regards,

**Comment by outscale-toa** [comment]
Hello @wibru,

we will close this issue,
If you still have a problem, please reopen it or create a new one.
Thanks,
