### ISSUE TITLE
How is it possible to set size of VM root partition and change type to GP2?

### ISSUE THREAD

**Issue by mgrechukh** [outscale-dev/terraform-provider-outscale#7]
VM reference https://github.com/outscale-dev/terraform-provider-outscale/blob/master/website/docs/r/vm.html.markdown describes how to add block devices to VM:

  block_device_mappings {
    device_name = "/dev/sdb"
    bsu         = {
      volume_size = 15
      volume_type = "gp2"
      snapshot_id = var.snapshot_id
    }
  
  block_device_mappings {
    device_name = "/dev/sdc"
    bsu         = {
      volume_size           = 22
      volume_type           = "io1"
      iops                  = 150
      delete_on_vm_deletion = true
    }
  }

When I do this, disks are actually visible inside VM as /dev/sda (instead of sdb) and /dev/sdb (instead of sdc)

But it also gives no clue on how to set **root** partition to be GP2 and/or change its size:

"""root_device_name - The name of the root device for the VM (for example, /dev/vda1).
root_device_type - The type of root device used by the VM (always bsu).""""

In AWS provider, for example, there is possible to provide complete root_block_device configuration block: The root_block_device mapping supports the following:

    volume_type - (Optional) The type of volume. Can be "standard", "gp2", "io1", "sc1", or "st1". (Default: "standard").
    volume_size - (Optional) The size of the volume in gibibytes (GiB).

**Comment by wibru** [comment]
Like this:

```
resource "outscale_vm" "test" {
[...]

  block_device_mappings {
    device_name = "/dev/sda1"
    bsu  {
      volume_size = 200
      volume_type = "gp2"
    }
  }
  ```
